Create a 2D matrix of shape (3, 4) with values from 1 to 12

Print the matrix, its shape, and transpose of the matrix

In [1]:
#!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,13,12).reshape(3,4)

In [4]:
arr

array([[ 8,  8, 12,  7],
       [10,  6,  3,  1],
       [12, 11,  2,  8]], dtype=int32)

In [5]:
np.shape(arr)

(3, 4)

In [6]:
arr.T

array([[ 8, 10, 12],
       [ 8,  6, 11],
       [12,  3,  2],
       [ 7,  1,  8]], dtype=int32)

In [7]:
np.shape(arr.T)

(4, 3)

Create a 5x5 matrix with values from 0 to 24
Extract:
- The 2nd row
- The 3rd column
- A 3x3 central submatrix

In [11]:
arr_2 = np.random.randint(0,25,25).reshape(5,5)

In [12]:
arr_2

array([[ 0,  5, 16, 11,  2],
       [ 1, 17, 24, 22, 17],
       [ 2,  8,  6,  1, 14],
       [12, 19,  7, 21, 21],
       [ 7, 15,  5, 12, 18]], dtype=int32)

In [14]:
arr_2[1:2,:]

array([[ 1, 17, 24, 22, 17]], dtype=int32)

In [15]:
arr_2[:,2:3]

array([[16],
       [24],
       [ 6],
       [ 7],
       [ 5]], dtype=int32)

In [18]:
arr_2[1:4,1:4]

array([[17, 24, 22],
       [ 8,  6,  1],
       [19,  7, 21]], dtype=int32)

Create a 1D array with 16 elements
Reshape it into:
- a 4x4 matrix
- a 2x8 matrix

Print both

In [24]:
arr3 = np.random.randint(0,100,size=16)

In [26]:
arr3.reshape(4,4)

array([[43, 87, 26, 49],
       [99, 49, 32, 33],
       [95, 56, 81, 37],
       [68, 45,  6,  5]], dtype=int32)

In [27]:
arr3.reshape(2,8)

array([[43, 87, 26, 49, 99, 49, 32, 33],
       [95, 56, 81, 37, 68, 45,  6,  5]], dtype=int32)

Create a 3x3 matrix of all ones

Create a 1D array: [1, 2, 3]

Add the 1D array to the matrix (broadcasting)

In [33]:
ones = np.ones((3,3))

In [34]:
arr_1d = np.array([1,2,3])

In [35]:
ones+arr_1d

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

Create matrix A of shape (2, 3)

Create matrix B of shape (3, 2)

Compute and print A @ B (dot product)

In [38]:
A = np.random.randint(0,11,6).reshape(2,3)

In [39]:
A

array([[10,  3,  7],
       [ 6,  3,  4]], dtype=int32)

In [40]:
B = np.random.randint(0,11,6).reshape(3,2)

In [41]:
B

array([[5, 0],
       [8, 3],
       [7, 8]], dtype=int32)

In [42]:
np.dot(A,B)

array([[123,  65],
       [ 82,  41]], dtype=int32)

Generate a random matrix of shape (3, 3)

Apply sigmoid activation: 1 / (1 + exp(-x)) to each element

In [43]:
arr_rand = np.random.randint(0,11,9).reshape(3,3)

In [44]:
arr_rand

array([[ 1,  6,  9],
       [10,  1,  8],
       [ 4, 10,  8]], dtype=int32)

In [45]:
1/(1+np.exp(-1 * arr_rand))

array([[0.73105858, 0.99752738, 0.99987661],
       [0.9999546 , 0.73105858, 0.99966465],
       [0.98201379, 0.9999546 , 0.99966465]])

X: input of shape (3, 1)

W: weights of shape (2, 3)

b: bias of shape (2, 1)

Compute Z = W.dot(X) + b

Apply sigmoid to Z to get A

In [55]:
X = np.random.randint(0,11,3).reshape(3,1)
X

array([[1],
       [5],
       [0]], dtype=int32)

In [56]:
W = np.random.randint(0,6,6).reshape(2,3)
W

array([[4, 3, 2],
       [4, 3, 0]], dtype=int32)

In [62]:
B = np.random.randint(0,6,2).reshape(2,1)
B

array([[0],
       [1]], dtype=int32)

In [63]:
Z = np.dot(W,X) + B
Z

array([[19],
       [20]], dtype=int32)

In [64]:
A = 1/(1+np.exp(-1 * Z))
A

array([[0.99999999],
       [1.        ]])

X: batch of 4 examples, each with 3 features → shape (3, 4)

W: weights → shape (2, 3)

b: bias → shape (2, 1)

Compute Z = W.dot(X) + b
Apply ReLU or Sigmoid

In [76]:
X = np.random.randint(0,11,12).reshape(3,4)
W = np.random.randint(0,11,6).reshape(2,3)
b = np.array([5,5]).reshape(2,1)

In [78]:
Z = np.dot(W,X) + b
Z

array([[103,  57,  53, 133],
       [125,  38,  65, 173]])

In [79]:
#Sigmoid
1/(1+np.exp(-1*Z))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Softmax

In [80]:
def softmax(x, axis):
    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))  # for numerical stability
    return e_x / np.sum(e_x, axis=axis, keepdims=True)

In [81]:
# Step 1: Create matrix Z of shape (3, 4)
Z = np.random.randn(3, 4)  # standard normal distribution
Z

array([[ 1.45088873,  0.122428  , -0.0371761 , -0.80115301],
       [-1.33811257, -0.66421111, -1.19801594, -0.97017234],
       [ 2.12092384,  0.92881842,  0.76796055, -1.3890554 ]])

In [82]:
# Step 2: Apply softmax along axis=0 (columns)
softmax_axis0 = softmax(Z, axis=0)
print("\nSoftmax along axis=0:\n", softmax_axis0)
print("Sum along axis=0 (should be 1):\n", np.sum(softmax_axis0, axis=0))


Softmax along axis=0:
 [[0.33158824 0.27062272 0.28167227 0.41666947]
 [0.0203869  0.12323419 0.08822624 0.35187428]
 [0.64802486 0.60614309 0.63010149 0.23145625]]
Sum along axis=0 (should be 1):
 [1. 1. 1. 1.]


In [83]:
# Step 3: Apply softmax along axis=1 (rows)
softmax_axis1 = softmax(Z, axis=1)
print("\nSoftmax along axis=1:\n", softmax_axis1)
print("Sum along axis=1 (should be 1):\n", np.sum(softmax_axis1, axis=1))


Softmax along axis=1:
 [[0.62661426 0.16598052 0.14149527 0.06590995]
 [0.17995265 0.3530449  0.20701483 0.25998762]
 [0.62815958 0.19069758 0.16236241 0.01878042]]
Sum along axis=1 (should be 1):
 [1. 1. 1.]


Given predictions A and true labels Y (both shape: (1, 4))

Calculate binary cross-entropy loss:

-loss = mean(Y * log(A) + (1 - Y) * log(1 - A))

In [92]:
A = np.array([0.99,0.04,0.68,0.1]).reshape(1,4)
Y = np.array([1,0,1,0])

In [93]:
loss = -1 * np.mean(Y*np.log(A)+(1-Y)*np.log(1-A))

In [94]:
loss

np.float64(0.1354738317108919)